[package]
name = "gblite"
version = "0.1.1"
authors = ["Austin Lasher <austin@lasher.email>"]

[dependencies]
num = "0.2"
ctrlc = { version = "3.0", features = ["termination"] }
sdl2 = { version = "0.31.0", features = ["bundled", "static-link"] }
